### ISSUE TITLE
トップページを作成

### ISSUE THREAD

**Issue by ywenli** [ywenli/todo#1]
# What's this?

簡易的なトップページを作ります。
機能やデザインはあとで追加していきます。

# TODO

- [x] gemの追加
  	- [x] bootstrap cf. https://github.com/twbs/bootstrap-rubygem
	- [x] haml cf. https://github.com/haml/haml-rails
	- [x] font-awesome-sass 
		cf. https://github.com/FortAwesome/font-awesome-sass
		cf. [Font Awesome Cheatsheet](https://fontawesome.com/6?next=%2Fcheatsheet%3Ffrom%3Dio)
- [x] topコントローラーの生成
- [x] アクションを追加 top#index
- [x] トップページのビューを作る
- [x] ルーティングを追加
- [x] ヘッダーを追加(パーシャル)
- [x] ヘッダーのscssを追加

# NOTE

gem追加した後は```docker build .```でコンテナを新しく立てる

**Comment by ywenli** [comment]
> gem追加した後はdocker build .でコンテナを新しく立てる

gemを追加する際に追加したgemのみインストールできる方法があるようです。
cf. https://qiita.com/k-penguin-sato/items/d51f09376f5733bb3ae9

**Comment by ywenli** [comment]
> > gem追加した後はdocker build .でコンテナを新しく立てる
> 
> gemを追加する際に追加したgemのみインストールできる方法があるようです。
> cf. [qiita.com/k-penguin-sato/items/d51f09376f5733bb3ae9](https://qiita.com/k-penguin-sato/items/d51f09376f5733bb3ae9)

こちらを参考にdocker-compose.ymlを編集して、新規gem追加時に新しいgemのみインストールするように変更しました。
